# Generated by Django 4.1 on 2022-09-27 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_image"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="image",),
    ]
